def pesquisa(rua):
    from .acrescimos import detalhes

    mapa = {'norte': {
        'binquinhas': ['beco do sinval', 'beco tiao', 'rua cel fortes', 'cel castro',
                       'nossa senhora da eucaristia',
                       'rua dos vicentinos', 'rua dos franciscanos', 'são tomas',
                       ],

        'campo alegre': ['adolfo lutz', 'adolfo bezerra de menezes', 'alcindo guanabara',
                         'albuquerque maranhao', 'alfredo lelis',
                         'alexandre de gusmao', 'amador bueno',
                         'andre reboucas', 'amintas de barros', 'balsa', 'bom jesus do livramento',
                         'caja', 'cambuca',
                         'carambola', 'choupo',
                         'cidra', 'cineraria', 'cipriano barata', 'conego januario barbosa',
                         'david canabarro',
                         'dom marcos teixeira', 'euclides miraglia',
                         'faia', 'francisco palheta', 'jarina', 'joao candido felisberto',
                         'jose benjamim de castro', 'lindolfo color', 'lotus', 'mangaba',
                         'manoel dias de abreu',
                         'maranata', 'matias de albuquerque', 'osorio duque estrada',
                         'pero lopes de souza', 'pedro labatut',
                         'praca francisco barreto',
                         'praca oswaldo aranha',
                         'praca placido de castro',
                         'rua dos bacuraus', 'soror ana angelica', 'u', 'um', 'vicente feola',
                         'vidal de negreiros'],

        'são bernado': ['abilio peres da silva', 'adonis', 'av cecilia pinto', 'av cristiano machado',
                        'av libania pena', 'av washington luiz', 'av waldomiro lobo', 'aderito tavora',
                        'america', 'antonio jose diniz', 'antonio moreira pacheco',
                        'armando ribeiro dos santos', 'bela vista', 'bernadino ventura', 'botafogo',
                        'caetano dias', 'conceicão silencio luciano', 'delvaux vicente luciano',
                        'dinorah ferreira messeder', 'doutor alberto horta', 'dr alberto horta',
                        'dr souza gomes', 'edna quintel', 'edson tomas santos', 'enrique tamn',
                        'flamengo', 'fluminense', 'francisco amancio ferreira', 'hero', 'francisco spino',
                        'joao lopes de oliveira', 'jose alves dos reis', 'josue sotte', 'kenedy',
                        'marcelo reginaldo gomes', 'maria amelia maia', 'padre antonio araujo',
                        'rua dos beneditinos', 'rua dos salesianos', 'sao cristovao', 'rosalina rocha',
                        'vasco da gama'],

        'heliopolis': ['abdenago lisboa', 'aguinaldo bicalho ervilha', 'Av cristiano machado',
                       'av waldomiro lobo',
                       'beco baronesa', 'belozina avelar zoroastro', 'benedito nogueira vilela',
                       'cel joaquim tiburcio', 'conego jose tomaz', 'dinah rocha mello',
                       'dinorah ferreira messeder', 'doutor alexandre sartori',
                       'doutor cinyras ladeira',
                       'francisco bittencourt', 'guilherme rangel correa', 'jose antenor',
                       'jose goncalves pimenta', 'jose joaquim duarte', 'josias vaz de oliveira',
                       'joventina da rocha', 'juiz humberto de paiva',
                       'laura brito farias', 'lila borja',
                       'lobo leite', 'maria amelia maia', 'maria manoela braz', 'mikhail nime safar',
                       'nair pentagna guimaraes', 'olbiano sausmikat',
                       'osmar costa', 'padre augusto',
                       'padre antonio', 'paulo do couto e silva', 'praca padre lage',
                       'professor heitor noronha',
                       'raimundo arruda', 'tenente edmundo messeder', 'yitzhak rabin',
                       ],

        'minas landia': ['abadia dos dourados', 'albertina', 'alcides de souza', 'aguas vermelhas',
                         'alirio ferreira de souza',
                         'arantina', 'aracitaba', 'aristides nonato dos santos', 'aurocitoba',
                         'av cristiano machado', 'e', 'egeu', 'etil',
                         'evangelista ferreira diniz', 'ezio mario terenzi', 'f', 'gomes de deus',
                         'jane eyre', 'jaceaba', 'joana darc', 'jose ambrosio diniz', 'jorn laercio campos',
                         'jose de alencar rogedo',
                         'jucelino jose diniz', 'maria adelaide', 'maria madalena esteves',
                         'maria ortiz', 'maria quiteria', 'marco polo', 'marquesa de santos', 'medeiros',
                         'monte virginia',
                         'paraibuna',
                         'paraopeba', 'parnaiba',
                         'penelope', 'perseu', 'professora maria sylvia',
                         'quatro', 'reis de almeida', 'rio das velhas', 'rio grande', 'rosalina bandeira',
                         'santa clara de assis', 'santa cruz', 'sao sebastiao', 'sinval l neves',
                         'sonia', 'travessa santa luzia', 'wander rocha vargas'],

        'são tomaz': ['armando couto', 'barao de coromandel', 'beco b', 'carlos tomas', 'comendador wigg',
                      'dez de novembro', 'dr jose rodrigues', 'geraldo antonio de freitas', 'imperatriz',
                      'maria amelia maia', 'maria candida', 'nelia', 'portugal', 'rua dos jesuitas',
                      'sao bento', 'sao tiago', 'sao luiz', 'santa bárbara', 'santa rosa',
                      'santo antonio', 'santa rita de cassia', 'tancredo esteves', 'visconde de morais'],

        'providencia': ['americo martins da costa', 'av risoleta neves', 'baldim', 'belo oriente',
                        'bertopolis', 'candido couto', 'careacu',
                        'casa grande', 'catas altas',
                        'cecilio emigdio saturnino',
                        'cinco de julho',
                        'coluna prestes', 'cristalia',
                        'datas', 'desterro do melo', 'dias', 'divinesia', 'divinesia', 'dom cavati',
                        'dona euzebia',
                        'doutor benedito xavier', 'doutor jafete abrahao', 'doutor nelio de morais',
                        'engenheiro navarro', 'ferros',
                        'felisburgo', 'florestal',
                        'francisco ferreira leite', 'fronteira', 'jacana',
                        'jose antenor de castro', 'jose olinto', 'jose vieira ferro velho', 'julio dias',
                        'madre dos anjos', 'manhuara', 'maravilhas',
                        'minaslandia', 'monsenhor messias',
                        'padre leopoldo', 'olimpio da silva lima', 'oscar lobo pereira', 'rua da pedreira',
                        'rua dos redentoristas', 'salvador ferraz', 'sao jorge', ],

        'planalto': ['adelina sales pereira', 'alfredo guzella', 'aloisio nogueira machado',
                     'anibal andrade camara', 'armando ziler',
                     'arthur lima de azevedo', 'av cristiano machado',
                     'av doutor cristiano guimaraes', 'av dom pedro primeiro',
                     'av general carlos guedes', 'av general olimpio mourao filho', 'barao de jacui',
                     'beco lourival carneiro',
                     'branca ferraz isoni', 'beija flor',
                     'capitao leonidio soares', 'carlyle guimaraes cardoso',
                     'cel castro', 'cel fortes', 'cel costa dias',
                     'cel leri santos',
                     'cel quintiliano valadares',
                     'david nasser', 'delio jose coelho', 'dina paula da silva',
                     'deputado ultimo de carvalho',
                     'dom carloto tavora', 'dom eugenio correia', 'doutor fabio fonseca',
                     'doutor jose ferolla', 'doutor miguel gontijo', 'doutor paes barreto',
                     'ely murilo claudio', 'epaminondas de moura e silva',
                     'francisco augusto rocha',
                     'fernando ferrari',
                     'frei hilario', 'guilherme da silveira', 'helio baggetti',
                     'helio salomao', 'henrique horta', 'herculano dias coelho',
                     'iracema souza pinto', 'irma celeste', 'joao fernandes de oliveira',
                     'joao de sales pires',
                     'jornalista fernando carvalho', 'jose benjamim de castro', 'jose bites peixoto',
                     'jose oscar barreira', 'josue azevedo', 'jorge de lima', 'judith alves pereira',
                     'lelio gama',
                     'lourival carneiro de vasconcelos',
                     'luiz de mello mattos', 'major avila goulart', 'maria ferreira dos santos',
                     'manoel xavier macedo', 'mardocheu diniz', 'marechal rondon',
                     'maria martins andrade',
                     'mario batista da costa', 'mauricio cardoso', 'me imperatriz',
                     'miguel aranha de azevedo', 'monsenhor negromonte', 'moura costa',
                     'monte alegre', 'newton pereira',
                     'nilo aparecida pinto',
                     'nossa sra da eucaritia', 'oliveira lima', 'osorio duque estrada',
                     'otavio nicolal', 'padre willian silva', 'pastor abreu',
                     'praca nossa senhora da paz',
                     'praca padre julio maria', 'praca vicente salles rezende',
                     'professora vicentina barreto', 'professor gentil sales',
                     'professor coelho junior',
                     'professor jose carvalho lopes', 'professor jose esteves',
                     'professor massanielo santos',
                     'professor tristao da cunha', 'professor teodoro vaz', 'recy souza paiva',
                     'risoleta pinto sardinha',
                     'roberto lucio aroeira', 'rodrigo osorio de andrade',
                     'rua dos bem te vis',
                     'rua dos carmelitas',
                     'rua dos jesuitas', 'rua das clarissas',
                     'rua dos maristas',
                     'rua dos sacramentinos',
                     'rua dos salesianos', 'rua dos trapistas', 'rua dos vicentinos', 'sesostris leal paixao',
                     'sao felix',
                     'sao jose do jacuri',
                     'sao tomas', 'senador campos vergueiro', 'senador carneiro de campos',
                     'stella navarro de miranda', 'terezinha lopes de azevedo',
                     'um', 'vereador orlando bonfim', 'vieira de campos', 'waldemar falcao',
                     'wilde jose pereira',
                     'wilsom soares fernandes', ],

        'vila aeroporto': ['beco da amizade', 'beco beira muro', 'beco dos esportes', 'beco santa rosa',
                           'beco sao bernardo', 'beco do joao pedro', 'eduardo quentel', 'rua d',
                           'rua da paz', 'praca dos esportes', 'santo elias', 'washington luiz'], },
        'noroeste': {
            'itapoã': ['arnaldo cardoso rocha', 'av portugal', 'branca raso assuncao',
                       'carlos alberto de freitas', 'carmo do paranaiba', 'conselheiro pena',
                       'desembargador custodio lustosa',
                       'desembargador lincoln prates', 'desembargador milton dos reis', 'dominica',
                       'dona queridinha',
                       'doutor jose esteves rodrigues',
                       'doutor luiz pena',
                       'doutor mario magalhaes', 'engenheiro vicente assuncao', 'fernando magalhaes gomes',
                       'guadalupe',
                       'general olimpio mourao filho', 'general ephigenio ruas santos',
                       'gilca cioto silva',
                       'geologo thomaz de aquino', 'gerson moretzsohn', 'gumercindo couto e silva',
                       'herbert brant aleixo',
                       'hesick muzzi', 'helen keller', 'honorina esteves giannetti',
                       'irlanda', 'jamaica', 'joao edmundo caldeira brant', 'joaquim victorino de souza',
                       'jornalista waldir lau',
                       'jose oscar barreira', 'libano',
                       'manoel lopes coelho', 'monte castelo', 'montese', 'min hermenegildo de barros',
                       'padre rodrigues', 'porto rico', 'plinio de mendonca', 'praca ercia barbosa santos',
                       'praca santa barbara',
                       'professor baeta viana',
                       'professor helio viana',
                       'professor herminio guerra',
                       'professor mercedo moreira', 'professor ricardo pinto',
                       'recy souza paiva',
                       'rosa maria savassi', 'roberto lucio aroeira', 'sapucai mirim', 'sao miguel',
                       'sao sebastiao do paraiso',
                       'sebastiao nepomuceno', 'vicenzo masi', ],

            'santa amelia': ['alair marques rodrigues', 'antonio egydio de lima', 'antonio scalzo',
                             'antonio julio barreto',
                             'augusto clementino',
                             'augusto moreira', 'augustus william parish',
                             'av guarapari', 'av dep anuar menhem', 'av min guilhermino de oliveira',
                             'av portugal', 'av virgilio de melo franco',
                             'carlos de sa',
                             'carlos marques', 'cel emilio martins',
                             'cristovao pinto ribeiro', 'com ary lopes',
                             'comendador teixeira da costa', 'dep feliciano pena',
                             'dep salim nacur', 'dep wilson tanure', 'detetive nelsom silva',
                             'domingos viotti', 'dona cidinha stussi', 'doutor hiran amaral',
                             'doutor jeferson de oliveira',
                             'edna brandao ferreira',
                             'edith araujo',
                             'eduardo cerqueira', 'engenheiro pedro bax', 'eurico lima gil', 'felipe joao bajur',
                             'fortunato pinto junior',
                             'francisco serrano neves', 'general patton', 'geraldino magalhaes de barros',
                             'heitor socrates cardoso',
                             'homero de oliveira', 'humberto rosa teixeira', 'irema maia freire',
                             'inacio murta', 'izabel lemos martins', 'joaquim goncalves braga',
                             'joaquim raymundo braga',
                             'joao de melo', 'joao fernades vieira', 'julio ferreira pinto', 'leiloeiro jose barros',
                             'levindo ignacio ribeiro',
                             'mansueto filizzola',
                             'maria da conceicao patrus',
                             'maria goncalves braga', 'maria candida cerqueira',
                             'mercia siqueira prates',
                             'muriae', 'nicola costa', 'norte de minas', 'olinda ferreira lopes',
                             'oeste de minas', 'oswaldo braga',
                             'particular',
                             'pioneiros da paz', 'praca 2269', 'professor benevenuto', 'professor clovis de faria',
                             'reynaldo smith camargos', 'rodrigo laje de oliveira',
                             'roque barreto da trindade', 'rua das canarias',
                             'rua das castanheiras',  'rua do mel', 'rua dos estados',
                             'rua dos expedicionarios', 'saide haddad antonio', 'sul de minas',
                             'tavares de melo', 'thomaz naves', 'triangulo mineiro', 'pelicano frade',
                             'zona da mata', ],

            'jardim atlantico': ['augusto clementino', 'augusto moreira', 'av otacilio negrao de lima', 'av portugal',
                                 'av sao tome do principe', 'av virgilio de melo franco', 'barao de camargos',
                                 'bento nogueira',
                                 'carlos sa', 'cheik nagib assrauy', 'gomes freire', 'eloi silva', 'ernesto braga',
                                 'faria lobato', 'francisco alves', 'josino de brito', 'juarez guimaraes de brito',
                                 'ilha grande',
                                 'manoel eustaquio', 'margarida', 'monte raso', 'paulo ribeiro bastos',
                                 'pelicano frade', 'rua das garopas', 'rua das malvinas',
                                 'rua do gandu', 'rua dos alcatrazes',
                                 'rua do arvoredo',
                                 'rua dos estados',
                                 'tavares de melo', 'tenerife',
                                 'thomaz naves', 'simao da cunha', ],


        },

        'pampulha': {
            'pampulha': ['a', 'aimee semple mcpherson', 'antonio paulino de castro', 'asa', 'a vinte e quatro',
                         'av presidente antonio carlos',
                         'av santa rosa',
                         'av professor magalhaes penido', 'bacupa', 'balsamar',
                         'boaventura', 'cacuera', 'cana verde', 'carmelino pinto coelho', 'cel fraga',
                         'doutor teles',
                         'emb afranio de melo franco',
                         'garuma', 'general aranha',
                         'henrique cabral', 'lider', 'jose soares neto',
                         'mascarenhas de morais', 'miramar', 'morse belem teixeira', 'noraldino de lima',
                         'padre silveira lobo', 'pedro dutra', 'praca bagatelle', 'praca santo antonio',
                         'professor almeida cunha',
                         'professor aurelio pires', 'professor jerson martins',
                         'professor nelson de sena', 'rua dos aeronautas', 'rua dos aeroviarios', ],

            'são luiz': ['a vinte e quatro', 'alameda das acacias', 'alameda das bauhinias', 'alameda das cariotas',
                         'alameda das falcatas', 'alameda do ipe amarelo', 'alameda das latanias',
                         'alameda das quaresmas',
                         'alameda das princesas', 'alameda do ipe branco', 'alameda dos coqueiros',
                         'alameda dos flamboyants',
                         'alameda dos jacarandas', 'alameda dos oitis',
                         'av alfredo camarate', 'av antonio abrahao caram', 'av c',
                         'av coronel jose dias bicalho',
                         'av coronel oscar paschoal', 'av das palmeiras',
                         'av dom orione',
                         'av expedicionario benvindo belem de lima', 'av otacilio negrao de lima',
                         'av presidente antonio carlos',
                         'av presidente carlos luz', 'av santa rosa', 'doutor fernando cenachi',
                         'doutor joao h mesquita',
                         'doutora helena lage', 'doutora silvia vinhas', 'expedicionario celso raciopi',
                         'expedicionario jose assuncao dos anjos',
                         'expedicionario mario alves de oliveira',
                         'expedicionario nilo morais pinheiro',
                         'expedicionario noraldino rosa santos',
                         'expedicionario paulo de oliveira', 'henrique cabral',
                         'jornalista wilson angelo',
                         'joubert guerra', 'mascarenhas de morais', 'maestro francisco flores',
                         'padre silveira lobo', 'praca alberto dalva simao',
                         'praca alfredo camarate', 'praca expedicionario lourival pereira',
                         'praca sao francisco de assis', 'professor almeida cunha',
                         'professor moacir gomes de freitas'],

            'são jose': ['alameda das acacias', 'alameda das latanias', 'alameda das princesas',
                         'alameda dos coqueiros',
                         'alexandre barbosa',
                         'artur itabirano',
                         'av antonio abrahao caram',
                         'av coronel jose dias bicalho', 'av presidente antonio carlos', 'barroso junior',
                         'carlos alves',
                         'joao luiz', 'leopoldino dos passos',
                         'rebelo horta',
                         'roquete mendonca', 'oliveira pena', ]},

        'oeste': {
            'bandeirantes': ['ancona', 'amalfi', 'av antonio francisco lisboa',
                             'av cremona', 'av heraclito mourao de miranda',
                             'av novara', 'av otacilio negrao de lima', 'av sicilia',
                             'av torino', 'av professor clovis salgado',
                             'basilicata', 'benito masci', 'bergamo',
                             'bianca', 'capri',
                             'carrara', 'calabria', 'campania', 'campo basso', 'chapada do norte',
                             'comendador gomes', 'coronel duraes', 'custodio pinto coelho',
                             'estanisiau fernandes', 'ferrara', 'florenca', 'golda meir', 'gregorio barrios',
                             'itatiaiucu', 'joao garzon', 'juiz jarbas ladeira', 'liguria',
                             'livorno', 'lodi', 'lombardia', 'maestro francisco buzelin',
                             'major messias menezes', 'messina', 'mondovi', 'orsi conceicao de minas',
                             'palermo',
                             'parma', 'pavia', 'pescara', 'piemonte', 'pisa', 'pistoia',
                             'polycarpo de magalhaes viotti',
                             'praca toscana', 'professor alberto deodato', 'professor rubens romanelli',
                             'renato travassos',
                             'rovigo', 'sardenha', 'sebastiao antonio carlos', 'siena', 'sorrento',
                             'taranto', 'tito alves pinto',
                             'trento', 'treviso',
                             'trieste', 'varese', 'verona',
                             'versilia', 'viterbo', ]
        },

        'sudoeste': {
            'ouro preto': ['adma saba paiva', 'ademar martins vieira', 'afonso raso', 'aluiso davis',
                           'agenor goulart filho',
                           'antonio augusto de carvalho',
                           'antonio marzinetti', 'antonio vergara lopes coelho',
                           'anita barbosa silva', 'anita blumberg', 'arnaldo bueno azevedo',
                           'apucarana'
                           'atilio grosso',
                           'augusto passos maia',
                           'austen nogueira de sa', 'av fleming', 'av sicilia',
                           'av antonio augusto da silva', 'av jose goncalves vidal',
                           'beco um', 'beco tres', 'beco cinco',
                           'beco oito', 'beco sete', 'belterra',
                           'bolivar de andrade', 'c', 'carlos frederico campos', 'conceicao do mato dentro',
                           'creco barbi',
                           'deputado andre de almeida',
                           'desembargador alarico barroso', 'desembargador leao starling',
                           'desembargador paula mota', 'desembargador pedro licinio', 'diomar souza e silva',
                           'domingos francis drumond', 'doutor geraldo zola mesquita', 'doutor julio soares',
                           'ecologia', 'erico de moura',
                           'engenho do sol',
                           'etel nogueira de sa', 'estanisiau fernandes', 'expedicionario celso raciopi',
                           'expedicionario paulo de oliveira', 'expedicionario jose assuncao dos anjos',
                           'flor de esparodia',
                           'flor de tipuana', 'forluminas', 'frei leopoldo', 'fuchal',
                           'geraldo bernardes de faria', 'geraldina candida de jesus', 'gerson blumberg',
                           'guarda custodio',
                           'guiomar paranhos',
                           'gulomar paranhos', 'jesus machado gontijo',
                           'joaquim henriques cardoso', 'jordania', 'jonas jean', 'jose amaral',
                           'jose faria tavares', 'jose guerra',
                           'jose gualberto de souza',
                           'jose henrique cardoso', 'joao antonio cardoso', 'joao afonso moreira',
                           'joao moreira da rocha',
                           'jose maria rosemburg',
                           'jose moura pecanha', 'juiz francisco horta',
                           'julio soares santana',
                           'luisa braz pena',
                           'luiz lopes', 'manoel elias de aguiar', 'mantena', 'maria francisca gomes',
                           'mariana oliveira tavares', 'marcos de oliveira', 'major lage', 'miralago',
                           'miraselvas',
                           'monteiro lobato', 'mozart bicalho', 'nizio torres',
                           'osorio de morais', 'otavio muniz carvalho', 'otaviano neves',
                           'paschoal carlos magno', 'pedro moreira de abreu', 'pedrogao pequeno',
                           'persio babo de resende',
                           'praca engenheiro jorge mansur',
                           'praca olga gatti barbosa', 'professor afonso dos santos', 'professor domicio murta',
                           'professor jose guerra', 'quarenta', 'professor manoel casassanta',
                           'ramiro athanasio de souza',
                           'randolfo trindade', 'sebastiao menezes silva', 'sena madureira', 'senador firmino',
                           'sergio miranda moreira', 'travessa herculano', 'uaproma', 'um', 'urarirama',
                           'valdiano martins inacio',
                           'yolanda de sa davis',
                           'wadi jose alau',
                           'welerson jean', 'zilah correia de araujo', ],
        }}

    for r, b in mapa.items():
        for nome_bairro, ruas in b.items():
            if rua in ruas:
                return detalhes(rua, r.title(), nome_bairro.title())
