def pesquisa(rua):

    from .acrescimos import detalhes

    mapa = {'norte': {
                    'binquinhas': ['beco do sinval', 'beco tiao', 'rua cel fortes', 'cel castro',
                                   'nossa senhora da eucaristia',
                                   'rua dos vicentinos', 'rua dos franciscanos', 'são tomas',
                                   ],
                    'são bernado': ['abilio peres da silva', 'adonis', 'av cecilia pinto', 'av cristiano machado',
                                    'av libania pena', 'av washington luiz', 'av waldomiro lobo', 'aderito tavora',
                                    'america', 'antonio jose diniz', 'antonio moreira pacheco',
                                    'armando ribeiro dos santos', 'bela vista', 'bernadino ventura', 'botafogo',
                                    'caetano dias', 'conceicão silencio luciano', 'delvaux vicente luciano',
                                    'dinorah ferreira messeder', 'doutor alberto horta', 'dr alberto horta',
                                    'dr souza gomes', 'edna quintel', 'edson tomas santos', 'enrique tamn',
                                    'flamengo', 'fluminense', 'francisco amancio ferreira', 'hero', 'francisco spino',
                                    'joao lopes de oliveira', 'jose alves dos reis', 'josue sotte', 'kenedy',
                                    'marcelo reginaldo gomes', 'maria amelia maia', 'padre antonio araujo',
                                    'rua dos beneditinos', 'rua dos salesianos', 'sao cristovao', 'rosalina rocha',
                                    'vasco da gama'],
        

                    'itapoã': ['arnaldo cardoso rocha', 'av portugal', 'branca raso assuncao',
                               'carlos alberto de freitas', 'carmo do paranaiba', 'conselheiro pena',
                               'desembargador custodio lustosa',
                               'desembargador lincoln prates', 'desembargador milton dos reis', 'dominica',
                               'dona queridinha',
                               'doutor jose esteves rodrigues',
                               'doutor luiz pena',
                               'doutor mario magalhaes', 'engenheiro vicente assuncao', 'fernando magalhaes gomes',
                               'guadalupe',
                               'general olimpio mourao filho', 'general ephigenio ruas santos',
                               'gilca cioto silva',
                               'geologo thomaz de aquino', 'gerson moretzsohn', 'gumercindo couto e silva',
                               'herbert brant aleixo',
                               'hesick muzzi', 'helen keller', 'honorina esteves giannetti',
                               'irlanda', 'jamaica', 'joao edmundo caldeira brant', 'joaquim victorino de souza',
                               'jornalista waldir lau',
                               'jose oscar barreira', 'libano',
                               'manoel lopes coelho', 'monte castelo', 'montese', 'min hermenegildo de barros',
                               'padre rodrigues', 'porto rico', 'plinio de mendonca', 'praca ercia barbosa santos',
                               'praca santa barbara',
                               'professor baeta viana',
                               'professor helio viana',
                               'professor herminio guerra',
                               'professor mercedo moreira', 'professor ricardo pinto',
                               'recy souza paiva',
                               'rosa maria savassi', 'roberto lucio aroeira', 'sapucai mirim', 'sao miguel',
                               'sao sebastiao do paraiso',
                               'sebastiao nepomuceno', 'vicenzo masi', ],
                    

                    'são tomaz': ['armando couto', 'barao de coromandel', 'beco b', 'carlos tomas', 'comendador wigg',
                                  'dez de novembro', 'dr jose rodrigues', 'geraldo antonio de freitas', 'imperatriz',
                                  'maria amelia maia', 'maria candida', 'nelia', 'portugal', 'rua dos jesuitas',
                                  'sao bento', 'sao tiago', 'sao luiz', 'santa bárbara', 'santa rosa',
                                  'santo antonio', 'santa rita de cassia', 'tancredo esteves', 'visconde de morais'],

                    'planalto': ['adelina sales pereira', 'alfredo guzella', 'aloisio nogueira machado',
                                 'anibal andrade camara', 'armando ziler',
                                 'arthur lima de azevedo', 'av cristiano machado',
                                 'av doutor cristiano guimaraes', 'av dom pedro primeiro',
                                 'av general carlos guedes', 'av general olimpio mourao filho', 'barao de jacui',
                                 'beco lourival carneiro',
                                 'branca ferraz isoni', 'beija flor',
                                 'capitao leonidio soares', 'carlyle guimaraes cardoso',
                                 'cel castro', 'cel fortes', 'cel costa dias',
                                 'cel leri santos',
                                 'cel quintiliano valadares',
                                 'david nasser', 'delio jose coelho', 'dina paula da silva',
                                 'deputado ultimo de carvalho',
                                 'dom carloto tavora', 'dom eugenio correia', 'doutor fabio fonseca',
                                 'doutor jose ferolla', 'doutor miguel gontijo', 'doutor paes barreto',
                                 'ely murilo claudio', 'epaminondas de moura e silva',
                                 'francisco augusto rocha',
                                 'fernando ferrari',
                                 'frei hilario', 'guilherme da silveira', 'helio baggetti',
                                 'helio salomao', 'henrique horta', 'herculano dias coelho',
                                 'iracema souza pinto', 'irma celeste', 'joao fernandes de oliveira',
                                 'joao de sales pires',
                                 'jornalista fernando carvalho', 'jose benjamim de castro', 'jose bites peixoto',
                                 'jose oscar barreira', 'josue azevedo', 'jorge de lima', 'judith alves pereira',
                                 'lelio gama',
                                 'lourival carneiro de vasconcelos',
                                 'luiz de mello mattos', 'major avila goulart', 'maria ferreira dos santos',
                                 'manoel xavier macedo', 'mardocheu diniz', 'marechal rondon',
                                 'maria martins andrade',
                                 'mario batista da costa', 'mauricio cardoso', 'me imperatriz',
                                 'miguel aranha de azevedo', 'monsenhor negromonte', 'moura costa',
                                 'monte alegre', 'newton pereira',
                                 'nilo aparecida pinto',
                                 'nossa sra da eucaritia', 'oliveira lima', 'osorio duque estrada',
                                 'otavio nicolal', 'padre willian silva', 'pastor abreu',
                                 'praca nossa senhora da paz',
                                 'praca padre julio maria', 'praca vicente salles rezende',
                                 'professora vicentina barreto', 'professor gentil sales',
                                 'professor coelho junior',
                                 'professor jose carvalho lopes', 'professor jose esteves',
                                 'professor massanielo santos',
                                 'professor tristao da cunha', 'professor teodoro vaz', 'recy souza paiva',
                                 'risoleta pinto sardinha',
                                 'roberto lucio aroeira', 'rodrigo osorio de andrade',
                                 'rua dos bem te vis',
                                 'rua dos carmelitas',
                                 'rua dos jesuitas', 'rua das clarissas',
                                 'rua dos maristas',
                                 'rua dos sacramentinos',
                                 'rua dos salesianos', 'rua dos trapistas', 'rua dos vicentinos', 'sesostris leal paixao', 'sao felix',
                                 'sao jose do jacuri',
                                 'sao tomas', 'senador campos vergueiro', 'senador carneiro de campos',
                                 'stella navarro de miranda', 'terezinha lopes de azevedo',
                                 'um', 'vereador orlando bonfim', 'vieira de campos', 'waldemar falcao',
                                 'wilde jose pereira',
                                 'wilsom soares fernandes', ],

                      'vila aeroporto': ['beco da amizade', 'beco beira muro', 'beco dos esportes', 'beco santa rosa',
                                         'beco sao bernardo', 'beco do joao pedro', 'eduardo quentel', 'rua d',
                                         'rua da paz', 'praca dos esportes', 'santo elias', 'washington luiz'], }

                     }

    for r, b in mapa.items():
        for nome_bairro, ruas in b.items():
            if rua in ruas:
                return detalhes(rua, r.title(), nome_bairro)
