# Generated by Django 4.1.7 on 2023-02-16 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localiza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='resposta2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.CharField(default='default_value', max_length=50)),
                ('rua', models.CharField(max_length=50)),
                ('regiao', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='resposta',
        ),
    ]
